
services:
  postgres:
    container_name: pg16
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatbot_db
      POSTGRES_INITDB_OPTIONS: "--encoding=UTF8 --locale=en_US.utf8 --lc-collate=en_US.utf8 --lc-ctype=en_US.utf8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/scripts/dbcreate.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  postgres_data: